"""Persistence of raw source documents and their processed representations.

Storage layout:
    <raw_data_dir>/<document_id>/<original_filename>
    <processed_data_dir>/<document_id>.json

Only the basename of the original filename is ever used, and the document ID
(a hex SHA-256 digest) is generated by the pipeline rather than caller input,
so persisted paths cannot escape the configured storage directories.
"""

from __future__ import annotations

import json
from pathlib import Path

from .exceptions import PersistenceError
from .models import NormalizedDocument


def raw_document_dir(raw_root: Path, document_id: str) -> Path:
    return raw_root / document_id


def raw_document_path(raw_root: Path, document_id: str, filename: str) -> Path:
    """Build the path a source file's raw bytes should be written to.

    Only `Path(filename).name` is used, so directory components (including
    `../` traversal attempts) in `filename` are discarded rather than honored.
    """
    safe_name = Path(filename).name
    if not safe_name or safe_name in {".", ".."} or "/" in filename or "\\" in filename:
        raise PersistenceError(f"Invalid source filename: {filename!r}")
    return raw_document_dir(raw_root, document_id) / safe_name


def processed_document_path(processed_root: Path, document_id: str) -> Path:
    return processed_root / f"{document_id}.json"


def write_raw(raw_root: Path, document_id: str, filename: str, data: bytes) -> Path:
    """Persist the exact raw bytes of a source document. Idempotent for identical input."""
    target = raw_document_path(raw_root, document_id, filename)
    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
    except OSError as exc:
        raise PersistenceError(f"Failed to write raw document to {target}: {exc}") from exc
    return target


def write_processed(processed_root: Path, document: NormalizedDocument) -> Path:
    """Persist the processed document as JSON, atomically.

    Serializes to a temporary file first and only replaces the final target
    once the write succeeds, so a failure never leaves a partial/corrupt file
    at the canonical path.
    """
    target = processed_document_path(processed_root, document.document_id)
    payload = json.dumps(document.to_dict(), indent=2, ensure_ascii=False)

    tmp_target = target.with_name(f"{target.name}.tmp")
    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        tmp_target.write_text(payload, encoding="utf-8")
        tmp_target.replace(target)
    except OSError as exc:
        tmp_target.unlink(missing_ok=True)
        raise PersistenceError(f"Failed to write processed document to {target}: {exc}") from exc
    return target


def load_processed(processed_root: Path, document_id: str) -> NormalizedDocument:
    """Load a previously persisted processed document back into memory.

    Works even if the original external source file no longer exists, since
    the processed JSON contains all metadata needed to reconstruct it.
    """
    target = processed_document_path(processed_root, document_id)
    try:
        raw_json = target.read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        raise PersistenceError(f"No processed document found for id {document_id!r}.") from exc
    except OSError as exc:
        raise PersistenceError(f"Failed to read processed document {target}: {exc}") from exc

    try:
        data = json.loads(raw_json)
    except json.JSONDecodeError as exc:
        raise PersistenceError(f"Processed document {target} is corrupt: {exc}") from exc

    return NormalizedDocument.from_dict(data)
